language: node_js
node_js:
  - "0.10"
#  - "0.11"
#  - "0.12"
#  - "io.js"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g gulp
  - npm install -g karma-cli

script: gulp mocha && karma start local.karma.conf.js

notifications:
  email: false

#addons:
#  sauce_connect:
#    username: "lapanoid"
#    access_key:
#      secure: "E3YG6yoCGJBJwkdEnUTmTZIaoARrEuu9a+8iE3zy8Tvb49eoY8NVSxwPPAGOv+/iAoEG9VL+BrvxyOiitpxk8BpCty412ppwRGRdlnTX+CsYmjoL+NkbnmFDlwU5BwXkxG5XaI50xdDzAYE/Rn4ADY09ATyHFyEspmuyQe4bZto=+r0f0H+GyE44B5KJovXQOt8JmCpX3QrLg="
