// Generated by CoffeeScript 1.8.0
(function() {
  var gulp, mocha, testsGlob;

  gulp = require("gulp");

  mocha = require("gulp-mocha");

  testsGlob = 'test/**/*.js';

  gulp.task('mocha', function() {
    return gulp.src(testsGlob, {
      read: false
    }).pipe(mocha({
      reporter: 'spec'
    }));
  });

}).call(this);

//# sourceMappingURL=gulpfile.js.map
